// final_soc_mm_interconnect_1.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module final_soc_mm_interconnect_1 (
		input  wire        clk_0_clk_clk,                                   //                             clk_0_clk.clk
		input  wire        pixel_dma_reset_reset_bridge_in_reset_reset,     // pixel_dma_reset_reset_bridge_in_reset.reset
		input  wire [31:0] pixel_dma_avalon_pixel_dma_master_address,       //     pixel_dma_avalon_pixel_dma_master.address
		output wire        pixel_dma_avalon_pixel_dma_master_waitrequest,   //                                      .waitrequest
		input  wire        pixel_dma_avalon_pixel_dma_master_read,          //                                      .read
		output wire [31:0] pixel_dma_avalon_pixel_dma_master_readdata,      //                                      .readdata
		output wire        pixel_dma_avalon_pixel_dma_master_readdatavalid, //                                      .readdatavalid
		input  wire        pixel_dma_avalon_pixel_dma_master_lock,          //                                      .lock
		output wire [16:0] frame_buffer_s2_address,                         //                       frame_buffer_s2.address
		output wire        frame_buffer_s2_write,                           //                                      .write
		input  wire [31:0] frame_buffer_s2_readdata,                        //                                      .readdata
		output wire [31:0] frame_buffer_s2_writedata,                       //                                      .writedata
		output wire [3:0]  frame_buffer_s2_byteenable,                      //                                      .byteenable
		output wire        frame_buffer_s2_chipselect,                      //                                      .chipselect
		output wire        frame_buffer_s2_clken                            //                                      .clken
	);

	wire         pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_waitrequest;   // frame_buffer_s2_translator:uav_waitrequest -> pixel_dma_avalon_pixel_dma_master_translator:uav_waitrequest
	wire  [31:0] pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_readdata;      // frame_buffer_s2_translator:uav_readdata -> pixel_dma_avalon_pixel_dma_master_translator:uav_readdata
	wire         pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_debugaccess;   // pixel_dma_avalon_pixel_dma_master_translator:uav_debugaccess -> frame_buffer_s2_translator:uav_debugaccess
	wire  [31:0] pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_address;       // pixel_dma_avalon_pixel_dma_master_translator:uav_address -> frame_buffer_s2_translator:uav_address
	wire         pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_read;          // pixel_dma_avalon_pixel_dma_master_translator:uav_read -> frame_buffer_s2_translator:uav_read
	wire   [3:0] pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_byteenable;    // pixel_dma_avalon_pixel_dma_master_translator:uav_byteenable -> frame_buffer_s2_translator:uav_byteenable
	wire         pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_readdatavalid; // frame_buffer_s2_translator:uav_readdatavalid -> pixel_dma_avalon_pixel_dma_master_translator:uav_readdatavalid
	wire         pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_lock;          // pixel_dma_avalon_pixel_dma_master_translator:uav_lock -> frame_buffer_s2_translator:uav_lock
	wire         pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_write;         // pixel_dma_avalon_pixel_dma_master_translator:uav_write -> frame_buffer_s2_translator:uav_write
	wire  [31:0] pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_writedata;     // pixel_dma_avalon_pixel_dma_master_translator:uav_writedata -> frame_buffer_s2_translator:uav_writedata
	wire   [2:0] pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_burstcount;    // pixel_dma_avalon_pixel_dma_master_translator:uav_burstcount -> frame_buffer_s2_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (0),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) pixel_dma_avalon_pixel_dma_master_translator (
		.clk                    (clk_0_clk_clk),                                                                        //                       clk.clk
		.reset                  (pixel_dma_reset_reset_bridge_in_reset_reset),                                          //                     reset.reset
		.uav_address            (pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (pixel_dma_avalon_pixel_dma_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (pixel_dma_avalon_pixel_dma_master_waitrequest),                                        //                          .waitrequest
		.av_read                (pixel_dma_avalon_pixel_dma_master_read),                                               //                          .read
		.av_readdata            (pixel_dma_avalon_pixel_dma_master_readdata),                                           //                          .readdata
		.av_readdatavalid       (pixel_dma_avalon_pixel_dma_master_readdatavalid),                                      //                          .readdatavalid
		.av_lock                (pixel_dma_avalon_pixel_dma_master_lock),                                               //                          .lock
		.av_burstcount          (1'b1),                                                                                 //               (terminated)
		.av_byteenable          (4'b1111),                                                                              //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                                 //               (terminated)
		.av_begintransfer       (1'b0),                                                                                 //               (terminated)
		.av_chipselect          (1'b0),                                                                                 //               (terminated)
		.av_write               (1'b0),                                                                                 //               (terminated)
		.av_writedata           (32'b00000000000000000000000000000000),                                                 //               (terminated)
		.av_debugaccess         (1'b0),                                                                                 //               (terminated)
		.uav_clken              (),                                                                                     //               (terminated)
		.av_clken               (1'b1),                                                                                 //               (terminated)
		.uav_response           (2'b00),                                                                                //               (terminated)
		.av_response            (),                                                                                     //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                                 //               (terminated)
		.av_writeresponsevalid  ()                                                                                      //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (17),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) frame_buffer_s2_translator (
		.clk                    (clk_0_clk_clk),                                                                        //                      clk.clk
		.reset                  (pixel_dma_reset_reset_bridge_in_reset_reset),                                          //                    reset.reset
		.uav_address            (pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (pixel_dma_avalon_pixel_dma_master_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (frame_buffer_s2_address),                                                              //      avalon_anti_slave_0.address
		.av_write               (frame_buffer_s2_write),                                                                //                         .write
		.av_readdata            (frame_buffer_s2_readdata),                                                             //                         .readdata
		.av_writedata           (frame_buffer_s2_writedata),                                                            //                         .writedata
		.av_byteenable          (frame_buffer_s2_byteenable),                                                           //                         .byteenable
		.av_chipselect          (frame_buffer_s2_chipselect),                                                           //                         .chipselect
		.av_clken               (frame_buffer_s2_clken),                                                                //                         .clken
		.av_read                (),                                                                                     //              (terminated)
		.av_begintransfer       (),                                                                                     //              (terminated)
		.av_beginbursttransfer  (),                                                                                     //              (terminated)
		.av_burstcount          (),                                                                                     //              (terminated)
		.av_readdatavalid       (1'b0),                                                                                 //              (terminated)
		.av_waitrequest         (1'b0),                                                                                 //              (terminated)
		.av_writebyteenable     (),                                                                                     //              (terminated)
		.av_lock                (),                                                                                     //              (terminated)
		.uav_clken              (1'b0),                                                                                 //              (terminated)
		.av_debugaccess         (),                                                                                     //              (terminated)
		.av_outputenable        (),                                                                                     //              (terminated)
		.uav_response           (),                                                                                     //              (terminated)
		.av_response            (2'b00),                                                                                //              (terminated)
		.uav_writeresponsevalid (),                                                                                     //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                                  //              (terminated)
	);

endmodule
