# TCL File Generated by Component Editor 18.1
# Sun Dec 08 01:45:18 CST 2019
# DO NOT MODIFY


# 
# Color_Mapper "Color_Mapper" v1.0
#  2019.12.08.01:45:18
# streamer that Maps colors from pallete so rgb
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Color_Mapper
# 
set_module_property DESCRIPTION "streamer that Maps colors from pallete so rgb"
set_module_property NAME Color_Mapper
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP ECE_385_Final
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Color_Mapper
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_color_mapper_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file avalon_color_mapper_interface.sv SYSTEM_VERILOG PATH avalon_color_mapper_interface.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point CLK
# 
add_interface CLK clock end
set_interface_property CLK clockRate 25000000
set_interface_property CLK ENABLED true
set_interface_property CLK EXPORT_OF ""
set_interface_property CLK PORT_NAME_MAP ""
set_interface_property CLK CMSIS_SVD_VARIABLES ""
set_interface_property CLK SVD_ADDRESS_GROUP ""

add_interface_port CLK CLK_clk clk Input 1


# 
# connection point RESET
# 
add_interface RESET reset end
set_interface_property RESET associatedClock CLK
set_interface_property RESET synchronousEdges DEASSERT
set_interface_property RESET ENABLED true
set_interface_property RESET EXPORT_OF ""
set_interface_property RESET PORT_NAME_MAP ""
set_interface_property RESET CMSIS_SVD_VARIABLES ""
set_interface_property RESET SVD_ADDRESS_GROUP ""

add_interface_port RESET RESET_reset reset Input 1


# 
# connection point RGB_SOURCE
# 
add_interface RGB_SOURCE avalon_streaming start
set_interface_property RGB_SOURCE associatedClock CLK
set_interface_property RGB_SOURCE associatedReset RESET
set_interface_property RGB_SOURCE dataBitsPerSymbol 8
set_interface_property RGB_SOURCE errorDescriptor ""
set_interface_property RGB_SOURCE firstSymbolInHighOrderBits true
set_interface_property RGB_SOURCE maxChannel 0
set_interface_property RGB_SOURCE readyLatency 0
set_interface_property RGB_SOURCE ENABLED true
set_interface_property RGB_SOURCE EXPORT_OF ""
set_interface_property RGB_SOURCE PORT_NAME_MAP ""
set_interface_property RGB_SOURCE CMSIS_SVD_VARIABLES ""
set_interface_property RGB_SOURCE SVD_ADDRESS_GROUP ""

add_interface_port RGB_SOURCE RGB_SOURCE_data data Output 24
add_interface_port RGB_SOURCE RGB_SOURCE_endofpacket endofpacket Output 1
add_interface_port RGB_SOURCE RGB_SOURCE_startofpacket startofpacket Output 1
add_interface_port RGB_SOURCE RGB_SOURCE_ready ready Input 1
add_interface_port RGB_SOURCE RGB_SOURCE_valid valid Output 1


# 
# connection point COLOR_ID_SINK
# 
add_interface COLOR_ID_SINK avalon_streaming end
set_interface_property COLOR_ID_SINK associatedClock CLK
set_interface_property COLOR_ID_SINK associatedReset RESET
set_interface_property COLOR_ID_SINK dataBitsPerSymbol 16
set_interface_property COLOR_ID_SINK errorDescriptor ""
set_interface_property COLOR_ID_SINK firstSymbolInHighOrderBits true
set_interface_property COLOR_ID_SINK maxChannel 0
set_interface_property COLOR_ID_SINK readyLatency 0
set_interface_property COLOR_ID_SINK ENABLED true
set_interface_property COLOR_ID_SINK EXPORT_OF ""
set_interface_property COLOR_ID_SINK PORT_NAME_MAP ""
set_interface_property COLOR_ID_SINK CMSIS_SVD_VARIABLES ""
set_interface_property COLOR_ID_SINK SVD_ADDRESS_GROUP ""

add_interface_port COLOR_ID_SINK COLOR_ID_SINK_1_data data Input 16
add_interface_port COLOR_ID_SINK COLOR_ID_SINK_startofpacket startofpacket Input 1
add_interface_port COLOR_ID_SINK COLOR_ID_SINK_endofpacket endofpacket Input 1
add_interface_port COLOR_ID_SINK COLOR_ID_SINK_ready ready Output 1
add_interface_port COLOR_ID_SINK COLOR_ID_SINK_valid valid Input 1

